// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhiqvTz7SUCnU4dvoJz5iH0JB4ihY8WtE',
    appId: '1:838836911296:web:2ed5491aa13d193f12c125',
    messagingSenderId: '838836911296',
    projectId: 't4-demo-b55bf',
    authDomain: 't4-demo-b55bf.firebaseapp.com',
    storageBucket: 't4-demo-b55bf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAgz8GIKMVBTljhqlCFJbU9P-orhy1Exg',
    appId: '1:838836911296:android:74d774ccf393a27f12c125',
    messagingSenderId: '838836911296',
    projectId: 't4-demo-b55bf',
    storageBucket: 't4-demo-b55bf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0ymsWjXCwfAx8SF0SxUbgaQehFciDEeA',
    appId: '1:838836911296:ios:57ca583adfcff5b512c125',
    messagingSenderId: '838836911296',
    projectId: 't4-demo-b55bf',
    storageBucket: 't4-demo-b55bf.appspot.com',
    iosBundleId: 'com.t4.demo.t4DemoFlutter',
  );
}
